### ISSUE TITLE
Support api 29

### ISSUE THREAD

**Issue by pierrekhouryy** [natario1/ViewPrinter#24]
This library works perfectly for my app on apis under 29. However on api 29 I have the following issue whenever I try to save a view as a pdf: 

`W/System.err: java.lang.RuntimeException: Could not create file.
        at com.otaliastudios.printer.Printer.checkFile(Printer.java:118)
        at com.otaliastudios.printer.PdfPrinter.print(PdfPrinter.java:54)
W/System.err:     at com.bimpos.insights.Fragments.Fr_Over.print(Fr_Over.java:954)
        at com.bimpos.insights.Fragments.Fr_Over.onOptionsItemSelected(Fr_Over.java:929)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2733)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2758)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:411)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:390)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
W/System.err:     at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
        at android.widget.AbsListView$3.run(AbsListView.java:4116)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/System.err: Caused by: java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at com.otaliastudios.printer.Printer.checkFile(Printer.java:115)
    	... 28 more
`

this is my code: 

`
File mDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        String mFilename = "pdf-" + System.currentTimeMillis();
        PdfPrinter mPdfPrinter = new PdfPrinter(mDocument, this);
        assert mDirectory != null;
        mPdfPrinter.print(PRINT_PDF, mDirectory, mFilename);`

**Comment by LucasCascao** [comment]
I'm with the same problem.

**Comment by pierrekhouryy** [comment]
@LucasCascao try this:

```
        File mDirectory;
        if (Build.VERSION.SDK_INT >= 29) {
            mDirectory = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);
        } else {
            mDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS);
        }
        PdfPrinter mPdfPrinter = new PdfPrinter(docView, this);
        assert mDirectory != null;
        mPdfPrinter.print(PRINT_PDF, mDirectory, mFilename);

```
